---
apiVersion: v1
kind: Namespace
metadata:
  name: py-ns
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: my-py-app-config-map
  namespace: py-ns
data:
  database: mongodb
  database_uri: mongodb://localhost:27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-py-app
  namespace: py-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-py-app
  template:
    metadata:
      labels:
        app: my-py-app
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: [ 'sh', '-c', "printenv" ]
        - name: init-mydb
          image: busybox:1.28
          command: [ 'sh', '-c', "printenv" ]
      containers:
        - name: my-py-app
          image: ojoadeolagabriel/my-py-app:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 50000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 50000
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 50000
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: my-py-app-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: my-py-app-service
  namespace: py-ns
spec:
  selector:
    app: my-py-app
  ports:
    - port: 50002
      targetPort: 50000
  type: LoadBalancer